In [ ]:
import torch

In [ ]:
x = torch.tensor(2.0, requires_grad=True)

In [ ]:
y = 2*x**4 + x**3 + 3*x**2 + 5*x + 1

In [ ]:
print(y)

tensor(63., grad_fn=<AddBackward0>)


In [ ]:
type(y)

torch.Tensor

In [ ]:
y.backward()

In [ ]:
x.grad

tensor(93.)

In [ ]:
x = torch.tensor([[1.,2.,3.],[3.,2.,1.]],requires_grad=True)

In [ ]:
print(x)

tensor([[1., 2., 3.],
        [3., 2., 1.]], requires_grad=True)


In [ ]:
y = 3*x + 2

In [ ]:
print(y)

tensor([[ 5.,  8., 11.],
        [11.,  8.,  5.]], grad_fn=<AddBackward0>)


In [ ]:
z = 2*y**2

In [ ]:
z

tensor([[ 50., 128., 242.],
        [242., 128.,  50.]], grad_fn=<MulBackward0>)

In [ ]:
out = z.mean()

In [ ]:
print(out)

tensor(140., grad_fn=<MeanBackward0>)


In [ ]:
out.backward()

In [ ]:
x.grad

tensor([[10., 16., 22.],
        [22., 16., 10.]])